import type { Metadata } from "next";
import { Oxanium, Roboto } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/features/providers/app-provider";
import { cn } from "@/lib/utils";

const oxaniumHeading = Oxanium({
	subsets: ["latin"],
	variable: "--font-heading",
});

const roboto = Roboto({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={cn(
				"h-full",
				"antialiased",
				roboto.variable,
				oxaniumHeading.variable,
			)}
			suppressHydrationWarning
		>
			<body className="min-h-full flex flex-col">
				<AppProvider>{children}</AppProvider>
			</body>
		</html>
	);
}
