import type { Metadata } from "next";
import { Oxanium, Roboto } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/features/providers/app-provider";
import { cn } from "@/lib/utils";

const oxaniumHeading = Oxanium({
    subsets: ["latin"],
    variable: "--font-heading",
    weight: ["500", "600", "700"],
});

const roboto = Roboto({
    subsets: ["latin"],
    variable: "--font-sans",
    weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn(
                "h-full",
                "antialiased",
                roboto.variable,
                oxaniumHeading.variable
            )}
            suppressHydrationWarning
        >
            <body className="flex min-h-full flex-col" suppressHydrationWarning>
                <AppProvider>{children}</AppProvider>
            </body>
        </html>
    );
}
